<?php
/*
	admin/config.php
	
	access: admin users only

	Allows administrators to change system-wide settings stored in the config table.
*/

class page_output
{
	var $obj_form;


	function check_permissions()
	{
		return user_permissions_get("admin");
	}

	function check_requirements()
	{
		// nothing to do
		return 1;
	}



	function execute()
	{
		/*
			Define form structure
		*/
		
		$this->obj_form = New form_input;
		$this->obj_form->formname = "config";
		$this->obj_form->language = $_SESSION["user"]["lang"];

		$this->obj_form->action = "admin/config-process.php";
		$this->obj_form->method = "post";


		// fetch fields and values from database
		$sql_obj		= New sql_query;
		$sql_obj->string	= "SELECT name, value FROM config ORDER BY name";
		$sql_obj->execute();

		if ($sql_obj->num_rows())
		{
			$sql_obj->fetch_array();
			
			// structure the results into a form we can then use to fill the fields in the form
			foreach ($sql_obj->data as $data)
			{
				$structure = NULL;
				$structure["fieldname"] = $data["name"];

				if ($structure["fieldname"] == "COMPANY_ADDRESS1_STREET" || $structure["fieldname"] == "COMPANY_PAYMENT_DETAILS")
				{
					$structure["type"] = "textarea";
				}
				else
				{
					// default to standard input
					$structure["type"] = "input";
				}
				
				$structure["defaultvalue"] = $data["value"];
				$this->obj_form->add_input($structure);
		
				$this->obj_form->subforms["program_options"][]	= $data["name"];
			}
		}


		// company logo
		$structure = NULL;
		$structure["fieldname"] 	= "COMPANY_LOGO";
		$structure["type"]		= "file";
		$this->obj_form->add_input($structure);
		
		$this->obj_form->subforms["program_options"][]	= "COMPANY_LOGO";
	
		$structure = NULL;
		$structure["fieldname"] 	= "COMPANY_MESSAGE";
		$structure["type"]		= "message";
		$structure["defaultvalue"]	= "Note: You only need to upload a logo once or when you want to replace it with a new logo. The logo will be used on PDF files generated by the billing system such as invoices.";
		$this->obj_form->add_input($structure);
		
		$this->obj_form->subforms["program_options"][]	= "COMPANY_MESSAGE";
			

		// submit section
		$structure = NULL;
		$structure["fieldname"] 	= "submit";
		$structure["type"]		= "submit";
		$structure["defaultvalue"]	= "Save Changes";
		$this->obj_form->add_input($structure);
		
		
		// define subforms
		$this->obj_form->subforms["submit"]		= array("submit");

		// no need to fetch form data, since this is done at the time of field creation.
	}



	function render_html()
	{
		// Title + Summary
		print "<h3>CONFIGURATION</h3><br>";
		print "<p>This page allows you to adjust the application configuration. Make sure you understand any options before adjusting them - refer to the product manual for help information.</p>";
	
		// display the form
		$this->obj_form->render_form();
	}

	
}

?>
