<?php
/*
	admin/templates.php
	
	access: admin users only

	Allows administrators to configure which template is used when generating PDF documents.
*/

class page_output
{
	var $obj_form;
	var $obj_sql_ar_invoice;


	function check_permissions()
	{
		return user_permissions_get("admin");
	}

	function check_requirements()
	{
		// nothing to do
		return 1;
	}


	function execute()
	{

		/*
			Fetch Template Information
		*/

		$this->obj_sql_ar_invoice		= New sql_query;
		$this->obj_sql_ar_invoice->string	= "SELECT id, active, template_file, template_name, template_description FROM templates WHERE template_type IN('ar_invoice_tex', 'ar_invoice_htmltopdf') ORDER BY id";
		$this->obj_sql_ar_invoice->execute();
		$this->obj_sql_ar_invoice->fetch_array();


		/*
			Define form structure
		*/
		
		$this->obj_form = New form_input;
		$this->obj_form->action = "admin/templates-process.php";
		$this->obj_form->method = "post";
	}



	function render_html()
	{
		// Title + Summary
		print "<h3>TEMPLATE SELECTION</h3><br>";
		print "<p>You can adjust the PDFs generated by the Amberdms Billing System by using different templates - these templates may include different languages, different layouts or other styling effects.</p>";

		// beta feature notice
		format_msgbox("important", "<p>Please note, this feature is currently in BETA and the template list is rather limited - Amberdms and the community are working on adding more templates and different languages as fast as possible. If you would like to help contribute different invoice templates, please join the mailing list or contact developers@amberdms.com</p>");
	
		// display the form
//		$this->obj_form->render_form();

		print "<form action=". $this->obj_form->action ." method=". $this->obj_form->method .">";


		/*
			AR INVOICES
		*/
		print "<br><br>";
		print "<h3>AR INVOICES</h3>";

		print "<table width=\"100%\">";
		print "<tr>";


		foreach ($this->obj_sql_ar_invoice->data as $data_sql)
		{
			// screenshot/icon
			print "<td><img src=\"". $data_sql["template_file"] ."_icon.png\"</td>";
		}


		print "</tr><tr>";


		foreach ($this->obj_sql_ar_invoice->data as $data_sql)
		{
			print "<td>";

			// details
			print "<p><b>". $data_sql["template_name"] ."</b></p>";
			print "<p>". $data_sql["template_description"] ."</p>";

			// select
			print "<input type=\"radio\" name=\"ar_invoice_tex\" value=\"". $data_sql["id"] ."\" ";

			if ($data_sql["active"])
			{
				print "checked ";
			}

			print "> ". lang_trans("use_this_template") ."";

			print "</td>";

		}

		
		print "</tr>";
		print "</table>";


		print "<br>";
		print "<input type=\"submit\" value=\"Save Changes\">";

		print "</form>";
	}

	
}

?>
